version: '3.6'

services:

  db_auth:
    image: postgres
    volumes:
      - pslq-auth:/var/lib/postgresql/auth
    environment:
      POSTGRES_PASSWORD: pass
    ports:
      - 5432:5432

  adminer:
    image: adminer
    ports:
      - 8081:8080

volumes:
  pslq-auth: